# Generated by Django 2.2.16 on 2022-02-27 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220227_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'произведение', 'verbose_name_plural': 'произведения'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Попытка регистрации пользователя под me-образным именем', regex='^[mM][eE]$')]),
        ),
    ]
